package com.fpicon.becas_fpicon;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Persona implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Nombre")
	private java.lang.String nombre;
	@org.kie.api.definition.type.Label(value = "Apellido")
	private java.lang.String apellido;
	@org.kie.api.definition.type.Label(value = "RUT")
	private java.lang.String rut;
	@org.kie.api.definition.type.Label(value = "Profesion")
	private java.lang.String profesion;
	@org.kie.api.definition.type.Label(value = "Fecha de nacimiento")
	private java.util.Date fechaNacimiento;

	public Persona() {
	}

	public java.lang.String getNombre() {
		return this.nombre;
	}

	public void setNombre(java.lang.String nombre) {
		this.nombre = nombre;
	}

	public java.lang.String getApellido() {
		return this.apellido;
	}

	public void setApellido(java.lang.String apellido) {
		this.apellido = apellido;
	}

	public java.lang.String getRut() {
		return this.rut;
	}

	public void setRut(java.lang.String rut) {
		this.rut = rut;
	}

	public java.lang.String getProfesion() {
		return this.profesion;
	}

	public void setProfesion(java.lang.String profesion) {
		this.profesion = profesion;
	}

	public java.util.Date getFechaNacimiento() {
		return this.fechaNacimiento;
	}

	public void setFechaNacimiento(java.util.Date fechaNacimiento) {
		this.fechaNacimiento = fechaNacimiento;
	}

	public Persona(java.lang.String nombre, java.lang.String apellido,
			java.lang.String rut, java.lang.String profesion,
			java.util.Date fechaNacimiento) {
		this.nombre = nombre;
		this.apellido = apellido;
		this.rut = rut;
		this.profesion = profesion;
		this.fechaNacimiento = fechaNacimiento;
	}

}